title: Lunar Sabbath
tagline: a time tested tradition
name: Daniel Larimer
user_description: Exploring God's Calendar Through Scripture and History
favicon: /assets/img/favicon.png
copyright_name: Daniel Larimer
baseurl: "" 
url: "https://lunarsabbath.net"
encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 
  - jekyll-seo-tag

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

# Collections for book content
collections:
  chapters:
    output: true
    permalink: /chapters/:name/
  facts:
    output: true
    permalink: /facts/:name/
  extras:
    output: true
    permalink: /extras/:name/
  symbols:
    output: true
    permalink: /symbols/:name/

defaults:
  - scope:
      path: ""
      type: chapters
    values:
      layout: chapter
      content-type: chapter
  - scope:
      path: ""
      type: facts
    values:
      layout: fact
      content-type: fact
  - scope:
      path: ""
      type: extras
    values:
      layout: chapter
      content-type: extra
  - scope:
      path: ""
      type: symbols
    values:
      layout: symbol
      content-type: symbol
